"""P0.1 GarminFitProvider tests.

Every FIT payload here is generated by `tests/fit_builder.py`; no real Garmin
export, API or credential is involved.
"""

from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import pytest
from click.testing import CliRunner
from fit_builder import SPORT_CYCLING, SyntheticActivity, build_fit

from trailcoach.core.config import settings
from trailcoach.db.models import (
    Activity,
    ActivityInterval,
    ActivityLink,
    ActivityStreamSet,
    Athlete,
    AthleteSourceAccount,
    DedupeReview,
    Device,
    MetricCapability,
    RawFile,
    SourceActivity,
    SourcePriority,
)
from trailcoach.ingest.orchestrator import IngestionOrchestrator
from trailcoach.ingest.raw_store import RawStore
from trailcoach.providers.fit_parser import FitParser
from trailcoach.sources import (
    GarminFitProvider,
    SourceProvider,
    SourceProviderRegistry,
)

BASE_START = datetime(2024, 3, 10, 7, 30, tzinfo=timezone.utc)


@pytest.fixture
def athlete(db):
    a = Athlete(display_name="Garmin Athlete")
    db.add(a)
    db.flush()
    return a


@pytest.fixture
def fit_dir(tmp_path) -> Path:
    d = tmp_path / "garmin_export"
    d.mkdir()
    return d


@pytest.fixture
def account(db, athlete, fit_dir):
    acc = AthleteSourceAccount(
        athlete_id=athlete.id,
        source="garmin_fit",
        auth_json={"import_dir": str(fit_dir)},
    )
    db.add(acc)
    db.flush()
    return acc


def write_fit(directory: Path, name: str, spec: SyntheticActivity) -> Path:
    p = directory / name
    p.write_bytes(build_fit(spec))
    return p


# ---------------------------------------------------------------------------
# Parser (pure stage)
# ---------------------------------------------------------------------------
def test_parse_bytes_extracts_summary_device_and_streams():
    spec = SyntheticActivity()
    doc = FitParser(source="garmin_fit").parse_bytes(build_fit(spec))

    assert doc.start_time == spec.start
    assert doc.sport == "running"
    assert doc.duration_elapsed_s == pytest.approx(spec.duration_s)
    assert doc.distance_m == pytest.approx(spec.distance_m)
    assert doc.ascent_m == pytest.approx(spec.ascent_m)
    assert doc.avg_hr is not None and spec.hr_start <= doc.avg_hr <= spec.hr_end
    assert doc.device.manufacturer == "garmin"
    assert doc.device.serial_number == str(spec.serial_number)
    assert doc.natural_id() == f"{spec.serial_number}-20240310T073000Z"

    rows = doc.canonical_stream_rows()
    assert len(rows) == spec.duration_s // spec.sample_interval_s + 1
    assert {"t_s", "hr_bpm", "lat", "lon", "distance_m", "altitude_m"} <= set(rows[0])
    assert rows[0]["lat"] == pytest.approx(spec.lat, abs=1e-5)
    assert len(doc.laps) == 1 and len(doc.sessions) == 1


def test_parse_bytes_is_deterministic_and_content_addressed():
    content = build_fit(SyntheticActivity())
    parser = FitParser(source="garmin_fit")
    assert parser.parse_bytes(content).sha256 == parser.parse_bytes(content).sha256
    other = build_fit(SyntheticActivity(hr_start=100))
    assert parser.parse_bytes(content).sha256 != parser.parse_bytes(other).sha256


# ---------------------------------------------------------------------------
# Provider contract
# ---------------------------------------------------------------------------
def test_provider_is_registered_and_implements_contract():
    cls = SourceProviderRegistry.get("garmin_fit")
    assert cls is GarminFitProvider
    assert issubclass(cls, SourceProvider)
    assert "garmin_fit" in SourceProviderRegistry.list_sources()
    assert "mock" in SourceProviderRegistry.list_sources()


def test_authenticate_validates_import_dir(db, athlete, fit_dir):
    provider = GarminFitProvider()

    missing = AthleteSourceAccount(athlete_id=athlete.id, source="garmin_fit")
    assert provider.authenticate(missing)["status"] == "error"

    bad = AthleteSourceAccount(
        athlete_id=athlete.id,
        source="garmin_fit",
        auth_json={"import_dir": str(fit_dir / "nope")},
    )
    assert provider.authenticate(bad)["auth_status"] == "import_dir_not_found"

    write_fit(fit_dir, "a.fit", SyntheticActivity())
    ok = AthleteSourceAccount(
        athlete_id=athlete.id, source="garmin_fit", auth_json={"import_dir": str(fit_dir)}
    )
    result = provider.authenticate(ok)
    assert result["status"] == "ok"
    assert result["auth_status"] == "not_required"
    assert result["file_count"] == 1


def test_capabilities_use_generic_metric_names(account):
    caps = GarminFitProvider().discover_capabilities(account)
    by_metric = {c.metric: c for c in caps}
    assert all(c.source == "garmin_fit" for c in caps)
    assert by_metric["heart_rate"].availability == "native"
    assert by_metric["gps"].availability == "native"
    assert by_metric["pace"].availability == "derived"
    assert by_metric["hrv"].availability == "unavailable"
    assert by_metric["sleep_score"].availability == "unavailable"


def test_get_wellness_is_empty_for_activity_fit(account):
    assert GarminFitProvider().get_wellness(account, date(2024, 1, 1), date(2024, 12, 31)) == []


def test_historical_range_and_date_filter(account, fit_dir):
    write_fit(fit_dir, "1.fit", SyntheticActivity(start=BASE_START))
    write_fit(
        fit_dir,
        "2.fit",
        SyntheticActivity(start=BASE_START + timedelta(days=5), serial_number=3_900_001_235),
    )
    write_fit(
        fit_dir,
        "3.fit",
        SyntheticActivity(start=BASE_START + timedelta(days=10), serial_number=3_900_001_236),
    )
    provider = GarminFitProvider()

    rng = provider.get_historical_range(account)
    assert rng.start == BASE_START.date()
    assert rng.end == (BASE_START + timedelta(days=10)).date()

    full = provider.initial_import(account)
    assert len(full.source_activities) == 3
    assert len(full.activities) == 3
    assert len(full.payloads) == 3

    window = provider.initial_import(
        account,
        start=(BASE_START + timedelta(days=4)).date(),
        end=(BASE_START + timedelta(days=6)).date(),
    )
    assert [sa.start_time_utc for sa in window.source_activities] == [
        BASE_START + timedelta(days=5)
    ]


def test_import_result_payload_and_links_account(account, fit_dir):
    spec = SyntheticActivity()
    write_fit(fit_dir, "run.fit", spec)
    result = GarminFitProvider().initial_import(account)

    sa = result.source_activities[0]
    assert sa.source == "garmin_fit"
    assert sa.account_id == account.id
    assert sa.source_activity_id == f"{spec.serial_number}-20240310T073000Z"
    assert sa.device_name == "garmin fr255_music"
    assert sa.provenance and sa.provenance["parser_version"] == FitParser.VERSION
    assert sa.provenance["raw_sha256"]

    payload = result.payloads[sa.source_activity_id]
    assert payload.raw_content == build_fit(spec)
    assert payload.raw_kind == "fit"
    assert payload.device == {
        "manufacturer": "garmin",
        "model": "fr255_music",
        "serial_number": str(spec.serial_number),
    }
    assert payload.stream_rows and payload.intervals
    assert result.cursor == {"last_start_time_utc": spec.start.isoformat()}

    assert GarminFitProvider().download_activity_file(
        account, sa.source_activity_id
    ) == build_fit(spec)
    assert GarminFitProvider().download_activity_file(account, "missing") is None


def test_incremental_sync_uses_account_cursor(account, fit_dir):
    write_fit(fit_dir, "1.fit", SyntheticActivity(start=BASE_START))
    provider = GarminFitProvider()

    first = provider.incremental_sync(account)
    assert len(first.source_activities) == 1
    account.cursor_json = first.cursor

    nothing = provider.incremental_sync(account)
    assert nothing.source_activities == []
    assert nothing.cursor == first.cursor

    write_fit(
        fit_dir,
        "2.fit",
        SyntheticActivity(start=BASE_START + timedelta(days=1), serial_number=1),
    )
    second = provider.incremental_sync(account)
    assert [sa.source_activity_id for sa in second.source_activities] == ["1-20240311T073000Z"]
    assert second.cursor["last_start_time_utc"] == (BASE_START + timedelta(days=1)).isoformat()


# ---------------------------------------------------------------------------
# Orchestrator: raw-first, dedup, device, provenance
# ---------------------------------------------------------------------------
def test_orchestrator_persists_raw_device_activity_and_provenance(db, account, fit_dir):
    spec = SyntheticActivity()
    write_fit(fit_dir, "run.fit", spec)

    summary = IngestionOrchestrator(db).run(account, GarminFitProvider())
    db.commit()

    assert summary.created == 1 and summary.failed == 0 and summary.errors == []

    raw = db.query(RawFile).one()
    assert raw.source == "garmin_fit"
    assert raw.kind == "fit"
    assert RawStore().read_bytes(raw) == build_fit(spec)

    device = db.query(Device).one()
    assert device.serial_number == str(spec.serial_number)
    assert device.manufacturer == "garmin"
    assert account.device_id == device.id

    sa = db.query(SourceActivity).one()
    assert sa.account_id == account.id
    assert sa.device_id == device.id
    assert sa.fit_raw_file_id == raw.id
    assert sa.provenance["raw_file_id"] == str(raw.id)
    assert sa.provenance["device_id"] == str(device.id)
    assert sa.provenance["account_id"] == str(account.id)

    activity = db.query(Activity).one()
    assert sa.canonical_activity_id == activity.id
    assert activity.primary_source == "garmin_fit"
    assert float(activity.distance_m) == pytest.approx(spec.distance_m)
    assert activity.provenance["source"] == "garmin_fit"
    assert activity.provenance["raw_file_id"] == str(raw.id)

    link = db.query(ActivityLink).one()
    assert link.match_method == "primary"
    assert link.source_activity_id == sa.id

    stream_set = db.query(ActivityStreamSet).one()
    assert stream_set.source_activity_id == sa.id
    assert "garmin_fit" in stream_set.storage_path
    assert (settings.processed_root_path / stream_set.storage_path).exists()
    assert stream_set.sample_count == spec.duration_s // spec.sample_interval_s + 1
    assert db.query(ActivityInterval).count() == 1

    caps = db.query(MetricCapability).filter_by(source="garmin_fit").all()
    assert {c.metric for c in caps} >= {"heart_rate", "gps", "hrv"}

    assert account.health == "ok"
    assert account.auth_status == "not_required"
    assert account.last_success_at is not None
    assert account.cursor_json == {"last_start_time_utc": spec.start.isoformat()}


def test_orchestrator_reimport_is_idempotent(db, account, fit_dir):
    write_fit(fit_dir, "run.fit", SyntheticActivity())
    orchestrator = IngestionOrchestrator(db)

    first = orchestrator.run(account, GarminFitProvider())
    second = orchestrator.run(account, GarminFitProvider())
    db.commit()

    assert first.created == 1
    assert second.reimported == 1 and second.created == 0
    assert db.query(SourceActivity).count() == 1
    assert db.query(Activity).count() == 1
    assert db.query(RawFile).count() == 1
    assert db.query(Device).count() == 1


def test_orchestrator_auto_links_same_activity_from_another_source(db, athlete, account, fit_dir):
    spec = SyntheticActivity()
    existing_activity = Activity(
        athlete_id=athlete.id,
        start_time_utc=spec.start,
        sport="running",
        primary_source="source_a",
        duration_elapsed_s=spec.duration_s,
        distance_m=spec.distance_m,
    )
    db.add(
        SourcePriority(
            athlete_id=athlete.id, metric="activity", priority=["garmin_fit", "source_a"]
        )
    )
    db.add(existing_activity)
    db.flush()
    db.add(
        SourceActivity(
            athlete_id=athlete.id,
            source="source_a",
            source_activity_id="ext-1",
            canonical_activity_id=existing_activity.id,
            start_time_utc=existing_activity.start_time_utc,
            duration_elapsed_s=spec.duration_s,
            distance_m=spec.distance_m,
            status="linked",
        )
    )
    db.flush()

    write_fit(fit_dir, "run.fit", spec)
    summary = IngestionOrchestrator(db).run(account, GarminFitProvider())
    db.commit()

    assert summary.linked == 1 and summary.created == 0
    assert db.query(Activity).count() == 1
    garmin_sa = db.query(SourceActivity).filter_by(source="garmin_fit").one()
    assert garmin_sa.canonical_activity_id == existing_activity.id
    link = db.query(ActivityLink).filter_by(source_activity_id=garmin_sa.id).one()
    assert link.match_method == "dedupe_auto"
    assert link.evidence["decision"] == "AUTO_LINK"
    assert db.query(RawFile).count() == 1


def test_orchestrator_keeps_ambiguous_match_for_review(db, athlete, account, fit_dir):
    spec = SyntheticActivity()
    existing_activity = Activity(
        athlete_id=athlete.id,
        start_time_utc=spec.start,
        sport="running",
        primary_source="source_a",
        duration_elapsed_s=spec.duration_s * 0.98,
        distance_m=spec.distance_m * 0.98,
    )
    db.add(existing_activity)
    db.flush()
    db.add(
        SourceActivity(
            athlete_id=athlete.id,
            source="source_a",
            source_activity_id="ext-2",
            canonical_activity_id=existing_activity.id,
            start_time_utc=existing_activity.start_time_utc,
            duration_elapsed_s=spec.duration_s * 0.98,
            distance_m=spec.distance_m * 0.98,
            status="linked",
        )
    )
    db.flush()

    write_fit(fit_dir, "run.fit", spec)
    summary = IngestionOrchestrator(db).run(account, GarminFitProvider())
    db.commit()

    assert summary.reviewed == 1
    review = db.query(DedupeReview).one()
    assert review.status == "pending"
    assert review.candidates["existing_canonical_activity_id"] == str(existing_activity.id)
    assert "final_score" in review.candidates["scores"]
    assert db.query(Activity).count() == 2
    garmin = db.query(Activity).filter_by(primary_source="garmin_fit").one()
    assert "dedupe_review_pending" in (garmin.quality_flags or [])


def test_orchestrator_keeps_different_activities_separate(db, account, fit_dir):
    write_fit(fit_dir, "run.fit", SyntheticActivity())
    write_fit(
        fit_dir,
        "ride.fit",
        SyntheticActivity(
            start=BASE_START + timedelta(hours=6),
            sport=SPORT_CYCLING,
            distance_m=40_000,
            duration_s=5400,
        ),
    )
    summary = IngestionOrchestrator(db).run(account, GarminFitProvider())
    db.commit()

    assert summary.created == 2
    assert db.query(DedupeReview).count() == 0
    assert {a.sport for a in db.query(Activity)} == {"running", "cycling"}
    assert db.query(Device).count() == 1


def test_orchestrator_isolates_corrupt_file(db, account, fit_dir):
    write_fit(fit_dir, "ok.fit", SyntheticActivity())
    (fit_dir / "broken.fit").write_bytes(b"not a fit file")

    summary = IngestionOrchestrator(db).run(account, GarminFitProvider())
    db.commit()

    assert summary.created == 1
    assert len(summary.errors) == 1 and summary.errors[0].startswith("broken.fit")
    assert db.query(Activity).count() == 1
    assert account.health == "ok"


def test_orchestrator_rejects_mismatched_provider(db, account):
    from trailcoach.sources import MockSourceProvider

    with pytest.raises(ValueError):
        IngestionOrchestrator(db).run(account, MockSourceProvider())


def test_orchestrator_marks_account_error_when_dir_missing(db, athlete, fit_dir):
    acc = AthleteSourceAccount(
        athlete_id=athlete.id,
        source="garmin_fit",
        auth_json={"import_dir": str(fit_dir / "missing")},
    )
    db.add(acc)
    db.flush()

    summary = IngestionOrchestrator(db).run(acc, GarminFitProvider())
    assert summary.processed == 0 and summary.errors
    assert acc.health == "error"
    assert acc.consecutive_failures == 1
    assert acc.auth_status == "import_dir_not_found"


# ---------------------------------------------------------------------------
# Legacy path stays intact
# ---------------------------------------------------------------------------
def test_legacy_fitfile_path_still_works(db, athlete, fit_dir):
    spec = SyntheticActivity()
    path = write_fit(fit_dir, "legacy.fit", spec)
    store = RawStore()
    raw = store.store_file(db, path, source="fitfile", kind="fit", athlete_id=athlete.id)
    parsed = FitParser(store).parse_to_source_activity(db, raw, athlete.id)
    db.commit()

    assert parsed.source.source == "fitfile"
    assert parsed.source.source_activity_id == raw.sha256
    assert parsed.activity is not None
    assert parsed.activity.primary_source == "fitfile"
    assert float(parsed.activity.distance_m) == pytest.approx(spec.distance_m)
    assert parsed.stream_set is not None


def test_cli_ingest_garmin_fit(monkeypatch, db, athlete, fit_dir):
    import trailcoach.cli.main as cli_main

    write_fit(fit_dir, "run.fit", SyntheticActivity())
    monkeypatch.setattr(cli_main, "SessionLocal", lambda: db)
    monkeypatch.setattr(db, "close", lambda: None)

    result = CliRunner().invoke(
        cli_main.cli, ["ingest-garmin-fit", str(fit_dir), "--athlete-id", str(athlete.id)]
    )
    assert result.exit_code == 0, result.output
    assert "created=1" in result.output
    acc = db.query(AthleteSourceAccount).filter_by(source="garmin_fit").one()
    assert acc.auth_json["import_dir"] == str(fit_dir.resolve())


def test_no_network_or_garminconnect_dependency():
    import importlib.util
    import sys

    import trailcoach.sources.garmin_fit  # noqa: F401

    loaded = set(sys.modules)
    assert not {m for m in loaded if m.startswith(("garminconnect", "requests", "httpx"))}
    assert importlib.util.find_spec("garminconnect") is None
