"""activity source metrics and zone times

Revision ID: 277b329b2dd0
Revises: 2ab1e2aa7123
Create Date: 2026-10-06 02:52:01.820021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277b329b2dd0'
down_revision: Union[str, Sequence[str], None] = '2ab1e2aa7123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_source_metric',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('source_activity_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('source_field', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_source_metric_activity_id_activity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_activity_id'], ['source_activity.id'], name=op.f('fk_activity_source_metric_source_activity_id_source_activity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_source_metric')),
    sa.UniqueConstraint('source_activity_id', 'metric', name=op.f('uq_activity_source_metric_source_activity_id'))
    )
    op.create_index(op.f('ix_activity_source_metric_activity_id'), 'activity_source_metric', ['activity_id'], unique=False)
    op.create_table('activity_zone_time',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('source_activity_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('zone_kind', sa.String(length=16), nullable=False),
    sa.Column('zone_index', sa.SmallInteger(), nullable=False),
    sa.Column('seconds', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('upper_bound', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('calc_basis', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_zone_time_activity_id_activity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_activity_id'], ['source_activity.id'], name=op.f('fk_activity_zone_time_source_activity_id_source_activity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_zone_time')),
    sa.UniqueConstraint('source_activity_id', 'zone_kind', 'zone_index', name=op.f('uq_activity_zone_time_source_activity_id'))
    )
    op.create_index(op.f('ix_activity_zone_time_activity_id'), 'activity_zone_time', ['activity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_zone_time_activity_id'), table_name='activity_zone_time')
    op.drop_table('activity_zone_time')
    op.drop_index(op.f('ix_activity_source_metric_activity_id'), table_name='activity_source_metric')
    op.drop_table('activity_source_metric')
    # ### end Alembic commands ###
