"""baseline

Revision ID: 2ab1e2aa7123
Revises: 
Create Date: 2026-09-11 18:04:33.180309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab1e2aa7123'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('tz_default', sa.String(length=64), nullable=False),
    sa.Column('units', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete'))
    )
    op.create_table('calc_version_registry',
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('stage', name=op.f('pk_calc_version_registry'))
    )
    op.create_table('event_inbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('subscription_id', sa.String(length=64), nullable=True),
    sa.Column('object_type', sa.String(length=32), nullable=True),
    sa.Column('aspect_type', sa.String(length=16), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_inbox'))
    )
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index(op.f('ix_job_dedupe_key'), 'job', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_job_kind'), 'job', ['kind'], unique=False)
    op.create_table('metric_capability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('availability', sa.String(length=16), nullable=False),
    sa.Column('confidence_base', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_capability')),
    sa.UniqueConstraint('source', 'metric', name=op.f('uq_metric_capability_source'))
    )
    op.create_index(op.f('ix_metric_capability_source'), 'metric_capability', ['source'], unique=False)
    op.create_table('platform',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_aggregator', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform')),
    sa.UniqueConstraint('slug', name=op.f('uq_platform_slug'))
    )
    op.create_table('activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time_local', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tz', sa.String(length=64), nullable=True),
    sa.Column('sport', sa.String(length=32), nullable=False),
    sa.Column('sub_sport', sa.String(length=32), nullable=True),
    sa.Column('primary_source', sa.String(length=32), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=True),
    sa.Column('duration_elapsed_s', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('duration_moving_s', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ascent_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('descent_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('avg_hr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_hr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_cadence', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_power', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('replaced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_race', sa.Boolean(), nullable=False),
    sa.Column('rpe', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_activity_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    op.create_index(op.f('ix_activity_sport'), 'activity', ['sport'], unique=False)
    op.create_index(op.f('ix_activity_start_time_utc'), 'activity', ['start_time_utc'], unique=False)
    op.create_index(op.f('ix_activity_sub_sport'), 'activity', ['sub_sport'], unique=False)
    op.create_table('athlete_state_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('state_version', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('quality', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_athlete_state_snapshot_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_state_snapshot')),
    sa.UniqueConstraint('athlete_id', 'as_of', 'state_version', name=op.f('uq_athlete_state_snapshot_athlete_id'))
    )
    op.create_table('athlete_threshold',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_athlete_threshold_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_threshold')),
    sa.UniqueConstraint('athlete_id', 'kind', 'valid_from', name=op.f('uq_athlete_threshold_athlete_id'))
    )
    op.create_table('athlete_zone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('zone_index', sa.SmallInteger(), nullable=False),
    sa.Column('lower', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('upper', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_athlete_zone_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_zone'))
    )
    op.create_table('daily_load',
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('load_primary', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('load_by_method', sa.JSON(), nullable=True),
    sa.Column('duration_s', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ascent_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('descent_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('vertical_work_j_per_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('n_activities', sa.Integer(), nullable=False),
    sa.Column('has_degraded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_daily_load_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id', 'date', name=op.f('pk_daily_load'))
    )
    op.create_table('device',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_device_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device')),
    sa.UniqueConstraint('athlete_id', 'serial_number', 'manufacturer', 'model', name=op.f('uq_device_athlete_id'))
    )
    op.create_index(op.f('ix_device_athlete_id'), 'device', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_device_serial_number'), 'device', ['serial_number'], unique=False)
    op.create_table('raw_file',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_activity_id', sa.String(length=128), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('parser_version', sa.String(length=16), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_raw_file_athlete_id_athlete'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_file'))
    )
    op.create_index(op.f('ix_raw_file_sha256'), 'raw_file', ['sha256'], unique=True)
    op.create_index(op.f('ix_raw_file_source_activity_id'), 'raw_file', ['source_activity_id'], unique=False)
    op.create_table('source_priority',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_source_priority_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_priority')),
    sa.UniqueConstraint('athlete_id', 'metric', name=op.f('uq_source_priority_athlete_id'))
    )
    op.create_index(op.f('ix_source_priority_athlete_id'), 'source_priority', ['athlete_id'], unique=False)
    op.create_table('source_state',
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('auth_status', sa.String(length=32), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('cursor', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_source_state_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id', 'source', name=op.f('pk_source_state'))
    )
    op.create_table('training_metric_daily',
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ctl', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('atl', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tsb', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ramp_rate_7d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('monotony_7d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('strain_7d', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ctl_ascent', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('atl_ascent', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('model_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_training_metric_daily_athlete_id_athlete'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('athlete_id', 'date', name=op.f('pk_training_metric_daily'))
    )
    op.create_table('activity_feature',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('feature_set_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=True),
    sa.Column('gap_avg_speed_mps', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ngp_mps', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('intensity_factor', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ascent_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('descent_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('vertical_work_j_per_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('climbing_rate_mph', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descent_rate_mph', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('technical_descent_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('hr_drift_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('decoupling_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('efficiency_index', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('time_in_hr_zone', sa.JSON(), nullable=True),
    sa.Column('time_in_pace_zone', sa.JSON(), nullable=True),
    sa.Column('time_in_grade_bin', sa.JSON(), nullable=True),
    sa.Column('best_efforts', sa.JSON(), nullable=True),
    sa.Column('mean_max_curve_path', sa.String(length=512), nullable=True),
    sa.Column('running_dynamics', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_feature_activity_id_activity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'feature_set_version', name=op.f('pk_activity_feature'))
    )
    op.create_table('activity_interval',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('start_s', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('end_s', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('start_distance_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('end_distance_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('duration_s', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ascent_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('descent_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('avg_hr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_hr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_speed_mps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_gap_speed_mps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_power_w', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_cadence', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_grade', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('vam_mph', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('detector_version', sa.String(length=16), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_interval_activity_id_activity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_interval'))
    )
    op.create_table('activity_load',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('selection_reason', sa.String(length=255), nullable=True),
    sa.Column('threshold_refs', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=16), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_load_activity_id_activity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_load')),
    sa.UniqueConstraint('activity_id', 'method', 'model_version', name=op.f('uq_activity_load_activity_id'))
    )
    op.create_table('athlete_source_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('platform_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('auth_json', sa.JSON(), nullable=True),
    sa.Column('cursor_json', sa.JSON(), nullable=True),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('auth_status', sa.String(length=32), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_athlete_source_account_athlete_id_athlete'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_athlete_source_account_device_id_device'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name=op.f('fk_athlete_source_account_platform_id_platform'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_source_account')),
    sa.UniqueConstraint('athlete_id', 'source', name=op.f('uq_athlete_source_account_athlete_id'))
    )
    op.create_index(op.f('ix_athlete_source_account_athlete_id'), 'athlete_source_account', ['athlete_id'], unique=False)
    op.create_table('source_activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_activity_id', sa.String(length=128), nullable=False),
    sa.Column('canonical_activity_id', sa.Uuid(), nullable=True),
    sa.Column('start_time_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('duration_elapsed_s', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('duration_moving_s', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ascent_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('sport_raw', sa.String(length=32), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('external_id_raw', sa.String(length=128), nullable=True),
    sa.Column('summary_raw_file_id', sa.Uuid(), nullable=True),
    sa.Column('fit_raw_file_id', sa.Uuid(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['athlete_source_account.id'], name=op.f('fk_source_activity_account_id_athlete_source_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_source_activity_athlete_id_athlete'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['canonical_activity_id'], ['activity.id'], name=op.f('fk_source_activity_canonical_activity_id_activity'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_source_activity_device_id_device'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fit_raw_file_id'], ['raw_file.id'], name=op.f('fk_source_activity_fit_raw_file_id_raw_file'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['summary_raw_file_id'], ['raw_file.id'], name=op.f('fk_source_activity_summary_raw_file_id_raw_file'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_activity')),
    sa.UniqueConstraint('source', 'source_activity_id', name=op.f('uq_source_activity_source'))
    )
    op.create_index(op.f('ix_source_activity_start_time_utc'), 'source_activity', ['start_time_utc'], unique=False)
    op.create_table('wellness_daily',
    sa.Column('athlete_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('resting_hr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('hrv_status', sa.String(length=16), nullable=True),
    sa.Column('hrv_ms', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('body_battery_min', sa.SmallInteger(), nullable=True),
    sa.Column('body_battery_max', sa.SmallInteger(), nullable=True),
    sa.Column('sleep_score', sa.SmallInteger(), nullable=True),
    sa.Column('sleep_duration_s', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('training_readiness', sa.SmallInteger(), nullable=True),
    sa.Column('vo2max', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('raw_file_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['athlete_source_account.id'], name=op.f('fk_wellness_daily_account_id_athlete_source_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], name=op.f('fk_wellness_daily_athlete_id_athlete'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_file_id'], ['raw_file.id'], name=op.f('fk_wellness_daily_raw_file_id_raw_file'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('athlete_id', 'date', 'source', name=op.f('pk_wellness_daily'))
    )
    op.create_table('activity_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_activity_id', sa.Uuid(), nullable=False),
    sa.Column('source_activity_id', sa.Uuid(), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_activity_id'], ['activity.id'], name=op.f('fk_activity_link_canonical_activity_id_activity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_activity_id'], ['source_activity.id'], name=op.f('fk_activity_link_source_activity_id_source_activity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_link')),
    sa.UniqueConstraint('source_activity_id', name=op.f('uq_activity_link_source_activity_id'))
    )
    op.create_table('activity_stream_set',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('source_activity_id', sa.Uuid(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('sample_rate_hz', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('series_type', sa.String(length=16), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('parser_version', sa.String(length=16), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('gap_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_activity_stream_set_activity_id_activity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_activity_id'], ['source_activity.id'], name=op.f('fk_activity_stream_set_source_activity_id_source_activity'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_stream_set')),
    sa.UniqueConstraint('source_activity_id', name=op.f('uq_activity_stream_set_source_activity_id'))
    )
    op.create_table('dedupe_review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_activity_id', sa.Uuid(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_activity_id'], ['source_activity.id'], name=op.f('fk_dedupe_review_source_activity_id_source_activity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dedupe_review'))
    )
    op.create_table('activity_stream_channel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stream_set_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('n_valid', sa.Integer(), nullable=False),
    sa.Column('n_missing', sa.Integer(), nullable=False),
    sa.Column('min', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('max', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('mean', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('p50', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('p95', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('is_derived', sa.Boolean(), nullable=False),
    sa.Column('calc_version', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stream_set_id'], ['activity_stream_set.id'], name=op.f('fk_activity_stream_channel_stream_set_id_activity_stream_set'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_stream_channel')),
    sa.UniqueConstraint('stream_set_id', 'channel', name=op.f('uq_activity_stream_channel_stream_set_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_stream_channel')
    op.drop_table('dedupe_review')
    op.drop_table('activity_stream_set')
    op.drop_table('activity_link')
    op.drop_table('wellness_daily')
    op.drop_index(op.f('ix_source_activity_start_time_utc'), table_name='source_activity')
    op.drop_table('source_activity')
    op.drop_index(op.f('ix_athlete_source_account_athlete_id'), table_name='athlete_source_account')
    op.drop_table('athlete_source_account')
    op.drop_table('activity_load')
    op.drop_table('activity_interval')
    op.drop_table('activity_feature')
    op.drop_table('training_metric_daily')
    op.drop_table('source_state')
    op.drop_index(op.f('ix_source_priority_athlete_id'), table_name='source_priority')
    op.drop_table('source_priority')
    op.drop_index(op.f('ix_raw_file_source_activity_id'), table_name='raw_file')
    op.drop_index(op.f('ix_raw_file_sha256'), table_name='raw_file')
    op.drop_table('raw_file')
    op.drop_index(op.f('ix_device_serial_number'), table_name='device')
    op.drop_index(op.f('ix_device_athlete_id'), table_name='device')
    op.drop_table('device')
    op.drop_table('daily_load')
    op.drop_table('athlete_zone')
    op.drop_table('athlete_threshold')
    op.drop_table('athlete_state_snapshot')
    op.drop_index(op.f('ix_activity_sub_sport'), table_name='activity')
    op.drop_index(op.f('ix_activity_start_time_utc'), table_name='activity')
    op.drop_index(op.f('ix_activity_sport'), table_name='activity')
    op.drop_table('activity')
    op.drop_table('platform')
    op.drop_index(op.f('ix_metric_capability_source'), table_name='metric_capability')
    op.drop_table('metric_capability')
    op.drop_index(op.f('ix_job_kind'), table_name='job')
    op.drop_index(op.f('ix_job_dedupe_key'), table_name='job')
    op.drop_table('job')
    op.drop_table('event_inbox')
    op.drop_table('calc_version_registry')
    op.drop_table('athlete')
    # ### end Alembic commands ###
